// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.simplezen.simple_permissions

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
private open class PermissionsPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/**
 * Host API for permission operations.
 *
 * Implemented in Kotlin, called from Dart.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PermissionsHostApi {
  /**
   * Checks which permissions from the list are currently granted.
   *
   * Returns a map of permission string → granted status.
   */
  fun checkPermissions(permissions: List<String>): Map<String, Boolean>
  /**
   * Requests the specified permissions from the user.
   *
   * Shows system permission dialogs. Returns map of permission → granted.
   * This is async because it waits for user interaction.
   */
  fun requestPermissions(permissions: List<String>, callback: (Result<Map<String, Boolean>>) -> Unit)
  /**
   * Checks if the specified role is currently held by this app.
   *
   * Common roles:
   * - `android.app.role.SMS` - Default SMS app
   * - `android.app.role.DIALER` - Default phone app
   */
  fun isRoleHeld(roleId: String): Boolean
  /**
   * Requests the specified role from the user.
   *
   * Shows system role request dialog. Returns true if granted.
   */
  fun requestRole(roleId: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Checks if the app is exempt from battery optimization.
   *
   * Battery optimization exemption is important for SMS apps to ensure
   * reliable message delivery when the phone is idle.
   */
  fun isIgnoringBatteryOptimizations(): Boolean
  /**
   * Requests exemption from battery optimization.
   *
   * Shows system dialog explaining the request. Returns true if granted.
   */
  fun requestIgnoreBatteryOptimizations(callback: (Result<Boolean>) -> Unit)
  /**
   * Checks Android rationale visibility for each permission.
   *
   * Returns permission -> shouldShowRationale.
   */
  fun shouldShowRequestPermissionRationale(permissions: List<String>): Map<String, Boolean>
  /**
   * Opens this app's system settings page.
   *
   * Returns true if the intent was started successfully.
   */
  fun openAppSettings(): Boolean

  companion object {
    /** The codec used by PermissionsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PermissionsPigeonCodec()
    }
    /** Sets up an instance of `PermissionsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PermissionsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_permissions.PermissionsHostApi.checkPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              listOf(api.checkPermissions(permissionsArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_permissions.PermissionsHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<String>
            api.requestPermissions(permissionsArg) { result: Result<Map<String, Boolean>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_permissions.PermissionsHostApi.isRoleHeld$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val roleIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.isRoleHeld(roleIdArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_permissions.PermissionsHostApi.requestRole$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val roleIdArg = args[0] as String
            api.requestRole(roleIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_permissions.PermissionsHostApi.isIgnoringBatteryOptimizations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isIgnoringBatteryOptimizations())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_permissions.PermissionsHostApi.requestIgnoreBatteryOptimizations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestIgnoreBatteryOptimizations{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_permissions.PermissionsHostApi.shouldShowRequestPermissionRationale$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              listOf(api.shouldShowRequestPermissionRationale(permissionsArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_permissions.PermissionsHostApi.openAppSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openAppSettings())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
