name: simple_permissions_android
description: Android implementation for the simple_permissions federated plugin.
version: 1.1.0
homepage: https://github.com/simplezen/simple-permissions
repository: https://github.com/simplezen/simple-permissions
issue_tracker: https://github.com/simplezen/simple-permissions/issues

environment:
  sdk: ^3.6.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  simple_permissions_platform_interface: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^22.7.0

flutter:
  plugin:
    implements: simple_permissions_native
    platforms:
      android:
        package: io.simplezen.simple_permissions_android
        pluginClass: SimplePermissionsAndroidPlugin
        dartPluginClass: SimplePermissionsAndroid
