include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    invalid_override_of_non_virtual_member: error
    override_on_non_overriding_member: error
