// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class PermissionsMacosPigeonCodecReader: FlutterStandardReader {
}

private class PermissionsMacosPigeonCodecWriter: FlutterStandardWriter {
}

private class PermissionsMacosPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PermissionsMacosPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PermissionsMacosPigeonCodecWriter(data: data)
  }
}

class PermissionsMacosPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PermissionsMacosPigeonCodec(readerWriter: PermissionsMacosPigeonCodecReaderWriter())
}


/// Host API for macOS permission operations.
///
/// Uses permission `identifier` strings (matching [Permission.identifier])
/// to avoid coupling native code to any specific Dart type hierarchy.
/// The Swift side uses a handler registry keyed on these identifiers.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PermissionsMacosHostApi {
  /// Check the current authorization status for a permission.
  ///
  /// Returns a wire string: "granted", "denied", "permanentlyDenied",
  /// "restricted", "limited", "notApplicable", "notAvailable", "provisional".
  func checkPermission(identifier: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Request authorization for a permission.
  ///
  /// Returns a wire string with the same values as [checkPermission].
  func requestPermission(identifier: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Whether the given permission identifier is supported on this macOS version.
  func isSupported(identifier: String) throws -> Bool
  /// Open this app's settings in System Settings (macOS 13+) / System Preferences.
  func openAppSettings(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PermissionsMacosHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PermissionsMacosPigeonCodec.shared }
  /// Sets up an instance of `PermissionsMacosHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PermissionsMacosHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Check the current authorization status for a permission.
    ///
    /// Returns a wire string: "granted", "denied", "permanentlyDenied",
    /// "restricted", "limited", "notApplicable", "notAvailable", "provisional".
    let checkPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_permissions_macos.PermissionsMacosHostApi.checkPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let identifierArg = args[0] as! String
        api.checkPermission(identifier: identifierArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkPermissionChannel.setMessageHandler(nil)
    }
    /// Request authorization for a permission.
    ///
    /// Returns a wire string with the same values as [checkPermission].
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_permissions_macos.PermissionsMacosHostApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let identifierArg = args[0] as! String
        api.requestPermission(identifier: identifierArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    /// Whether the given permission identifier is supported on this macOS version.
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_permissions_macos.PermissionsMacosHostApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let identifierArg = args[0] as! String
        do {
          let result = try api.isSupported(identifier: identifierArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    /// Open this app's settings in System Settings (macOS 13+) / System Preferences.
    let openAppSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_permissions_macos.PermissionsMacosHostApi.openAppSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openAppSettingsChannel.setMessageHandler { _, reply in
        api.openAppSettings { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openAppSettingsChannel.setMessageHandler(nil)
    }
  }
}
